version: '1.0.0'
services:
  app:
    build: .
    container_name: empresaXYZ-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/meubanco
      SPRING_DATASOURCE_USERNAME: meuuser
      SPRING_DATASOURCE_PASSWORD: minhasenha

  db:
    image: mysql:8
    container_name: empresaXYZ-db
    environment:
      MYSQL_DATABASE: meubanco          # Nome do banco de dados a ser criado
      MYSQL_USER: meuuser               # Nome do usuário não-root a ser criado
      MYSQL_PASSWORD: minhasenha        # Senha do usuário não-root
      MYSQL_ROOT_PASSWORD: rootpass     # Senha do usuário root (obrigatório)
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
